name = "vegamovies-api"
main = "worker.ts"
compatibility_date = "2024-04-08"

# Required for Cheerio and other Node.js libraries to work in Cloudflare Workers
compatibility_flags = [ "nodejs_compat" ]
